services:
  _defaults:
    autowire: true
    autoconfigure: true

  Meromn\UseCaseGenerator\Command\UseCaseGeneratorCommand: ~
  Meromn\UseCaseGenerator\Contracts\Service\UseCaseGeneratorServiceInterface:
    alias: Meromn\UseCaseGenerator\Service\UseCaseGeneratorService

  Meromn\UseCaseGenerator\Service\UseCaseGeneratorService:
    public: true
    arguments:
      - ''
      - ''
      - ''
      - ''
      - ''
      - ''
      - ''
      - '%kernel.project_dir%'